kernelcraft/run.py
kernelcraft/utils.py
setup.py

The message about missing file still reflect the older /etc/ path, but it shouldn't be a problem for older and new new users. Also, convert configuration paths to uppercase.

setup: Fallback to /etc/kernelcraft.conf file .config doesn't exists

---

virtme/commands/configkernel.py
virtme/commands/run.py
virtme/mkinitramfs.py
virtme/virtmods.py

Virtiofs is a shared file system that lets virtual machines access a directory tree on the host. Unlike existing approaches, it is designed to offer local file system semantics and performance [1].
Compared to the 9P filesystem, virtio-fs offers consistent performance advantages by delivering access times that closely approach the native performance of the host filesystem.
Test case:
- Run `git diff` from a linux git repo
Results:
9p-fs: 283.814s
virtio-fs:   1.174s
Speed up in this particular case is approximately 241.96 times faster.
Virtme will try to automatically enable the new virtio-fs support: if virtiofsd is found in the $PATH or in /usr/libexec, it'll be used to export the host's rootfs and qemu options will be automatically adjusted to use it. Otherwise virtme will fall-back to …

virtme: support virtio-fs

---

virtme/commands/run.py

In my local kernel build, the output of "file bzImage" shows Version, instead of the expected version string:
$ file arch/x86/boot/bzImage
arch/x86/boot/bzImage: Linux/x86 Kernel, Setup Version 0x20f, bzImage, Version 6.4.0-rc3+ ...
So this fix makes virtme-run to work on current openSUSE Tumbleweed.

run.py: Fix get_kernel_version by checking for "Version" string

---

virtme/architectures.py
virtme/commands/configkernel.py
virtme/commands/run.py
virtme/guest/virtme-init
virtme_ng/run.py

Allow to run individual graphical applications inside a virtme-ng session.
Change the `--graphics / -g` option to accept an optional argument. If an argument is passed, it will be interpreted as a graphical application to run inside a virtme-ng session.
virtme-ng will simply use `xinit` with a bare minimum `.xinitrc` to start the application in a minimal X graphical environment.
This is the first prototype of the functionality mentioned in issue #15.

virtme-ng: allow to run graphical applications

---

virtme/guest/virtme-init

we don't need this, we can just mount cgroupv2 directly.

don't use a tmpfs for cgroupv2

---

.gitignore
build-deb.sh
debian/control
setup.py
virtme/commands/run.py
virtme_ng_init/Cargo.toml
virtme_ng_init/README.md
virtme_ng_init/src/main.rs
virtme_ng_init/src/utils.rs

Overview
=======
virtme-ng-init is an extremely lightweight init process for virtme-ng implemented in Rust, as a replacement of the Bash virtme-init implementation.
Its primary goal is to speed up the boot time of virtme-ng instances.
virtme-ng-init is able to perform any necessary initialization in the virtualized environment required by virtme-ng, such as mounting filesystems, starting essential services, and configuring the system before handing over control to the main user-space processes.
NOTE: at the moment virtme-ng-init is only used when running native architecture instances.
Result
======
- virtme-init (Bash implementation):
```
$ time virtme-ng --exec 'uname -r'
6.4.0-rc3-virtme
real	0m1.146s
user	0m0.829s
sys	0m1.048s
$ time virtme-ng --net user --exec 'ip addr show dev eth0' …
```

guest: introduce virtme-ng-init

---

README.md
setup.py
virtme/commands/configkernel.py
virtme/commands/run.py
virtme/guest/virtme-init
virtme/guest/virtme-snapd-script
virtme_ng/run.py
virtme_ng_init/src/main.rs
virtme_ng_init/src/utils.rs

Enable all the required (kernel and user-space) features to start snapd and execute snaps directly inside a virtme-ng instance.
The snap support is activated only if snapd is installed in the host system. This won't introduce any additional overhead in systems that don't have snap available.
In systems that have snapd available, virmte-ng will automatically start it at boot (tricking it a bit into believing that it's running in a standard systemd-enabled environment) and at this point we can start any snap as regular system binaries inside virtme-ng.
This fixes issue #21.
Open issues
===========
The main issue at the moment is that the guest requires read access to `/var/lib/snapd/state.json` that has `0600` permissions by default. Since we are running the guest as unprivileged user, by …

virtme-ng: allow to run snaps inside virtme-ng instances

---

virtme_ng/run.py

Python documentation recommends the `getpass.getuser()` as a more portable and reliable alternative (at least inside Python, since thats not POSIX) of `os.getlogin()`.

Use getpass.getuser() instead of os.getlogin()

---

bin/virtme-prep-kdir-mods

If a virtme user tries to execute virtme-prep-kdir-mods on a distribution that is already converted to usrmerge depmod error out:
$ virtme-prep-kdir-mods
depmod: ERROR: could not open directory /home/mpdesouza/git/linux/.virtme_mods/usr/lib/modules/0.0.0: No such file or directory depmod: FATAL: could not search modules: No such file or directory
A simple symlink can fix the problem. The new link will be called usr and will point to the existing lib/modules directory that was already being created by the script.

virtme-prep-kdir-mods: Fix depmod invocation on usrmerge'd distros

---

virtme/commands/run.py

Some distributions like openSUSE don't append /sbin or /usr/sbin to the default PATH, leading to issues when trying to execute depmod.
This patch adapts the same approach done on
95630104d888 ("virtme-prep-kdir-mods: Add /usr/sbin to $PATH").

virtme-run: Find the exact location of depmod

---

virtme_ng/run.py

Currently a space is missed in creating the user added overlay directories.
I believe this requires not using `--rw`

overlay-rwdir: Fix the command

---

virtme_ng/run.py

The argcomplete dependency isn't critical, so let's continue on in its absence instead of blowing up (convenient for running the 'vng' command directly from the source tree without having to install any python module dependencies).

virtme-ng: Don't fail on missing argcomplete

---

Makefile
setup.py

This is primarily just a small convenience for building an updated virtme-ng-init when running vng from the source directory.  In order to keep the definition of "how to build init" in one place, also update setup.py to run 'make' instead of directly invoking 'cargo'.

Add tiny Makefile for building virtme-ng-init

---

virtme/guest/virtme-init
virtme_ng/run.py

With virtme-ng defaulting to running as the current user instead of root, I've been finding it easy to get confused about whether my shell prompt (which includes the hostname) is from the host or the guest (since they end up identical).  Providing a recognizable default for the `--name` flag makes it easier to tell them apart.

virtme-ng: Set a default for --name

---

virtme/guest/virtme-init

otherwise we get:
mount: /etc/sudoers: mount point does not exist.

virtme-init: touch /etc/sudoers if it doesn't exist

---

virtme/guest/virtme-init

Otherwise we end up with:
/run/virtme/guesttools/virtme-init: line 51: cannot redirect standard input from /dev/null: No such file or directory
/run/virtme/guesttools/virtme-init: line 52: cannot redirect standard input from /dev/null: No such file or directory
/run/virtme/guesttools/virtme-init: line 55: cannot redirect standard input from /dev/null: No such file or directory
/run/virtme/guesttools/virtme-init: line 56: cannot redirect standard input from /dev/null: No such file or directory
/run/virtme/guesttools/virtme-init: line 57: cannot redirect standard input from /dev/null: No such file or directory
/run/virtme/guesttools/virtme-init: line 58: cannot redirect standard input from /dev/null: No such file or directory
/run/virtme/guesttools/virtme-init: line 62: cannot redirect …

virtme-init: mount devtmpfs before using bash redirects

---

requirements.txt
virtme_ng/mainline.py
virtme_ng/run.py
virtme_ng/utils.py

This is a PoC of an idea discussed with @marcosps at LPC 2023 in Richmond (VA): use pre-compiled kernels to get rid of the build time when we need to recompile specific kernel versions.
For the pre-compiled kernels we can rely on the Ubuntu mainline repository: Ubuntu periodically provides deb packages for the main upstream kernel versions (for debugging purposes), that are essentially vanilla kernels with the generic Ubuntu `.config`, so they are general-purpose kernels suitable for any kind of test.
This can help to speed up time (and energy :green_heart:) when we need to test specific upstream kernel versions, by cutting completely the kernel rebuild time.
See commit description for implementation details and usage.
Feedbacks are welcome!

virtme-ng: use pre-compiled mainline kernels

---

setup.py

If vng is installed using pipx, which starts a venv by default for the installed package, fails to find requests library. Add requests as a requirements of vng so it can be found correctly by pipx.

setup.py: Add requests to install_requires

---

virtme/guest/virtme-init

When using vng without the --no-virtme-ng-init, running a command that resides on /sbin with sudo doesn't work:
$ vng --no-virtme-me-init
$ mpdesouza@virtme-ng:~/git/linux> modprobe
Absolute path to 'modprobe' is '/usr/sbin/modprobe', so running it may require superuser privileges (eg. root). $ mpdesouza@virtme-ng:~/git/linux> sudo modprobe
sudo: modprobe: command not found
In essence, the path when running sudo is the same of the normal user. Fix this problem by creating a secure_path when running with sudo, which includes /sbin  and usr/sbin along with the common binary paths. With the fix applied, modprobe is found as expected:
$ vng --no-virtme-me-init
$ mpdesouza@virtme-ng:~/git/linux> modprobe
Absolute path to 'modprobe' is '/usr/sbin/modprobe', so running it may require superuser …

virtme-init: Add default secure_path

---

virtme/commands/run.py

The get_rootfs_from_kernel_path() function finds a candidate location for kernel modules by walking directories starting from the kimg location up to the root of the file system, and checking for a lib/modules/ subdirectory in each of them. This process repeats until the file system root, "/", is reached.
If kimg is not an absolute path, the path variable in the loop will eventually become an empty string, without ever being equal to "/". The loop will then run forever. Fix it by stopping when the path is an empty string. This will return an empty string as the modules' root directory, and the caller will disable handling of modules.

virtme: Fix infinite loop when finding kernel modules

---

virtme/guest/virtme-init

Some distributions, e.g. openSUSE, doesn't create a group for the user, but rather assigns the user to 'users' group. Without this patch, there is an error being issues on openSUSE:
chown: invalid group: 'mpdesouza:mpdesouza'
Fix it by checking which groups are available. If a group isn't found, chown doesn't error out when 'chown user: file' is used.

virtme-init: Check if virtme_user is a valid group

---

.github/workflows/run.yml
README.md
virtme/commands/run.py
virtme/guest/virtme-init
virtme_ng/run.py

Set of changes to properly support running virtme-ng instances inside docker instances.
This will open the possibility for many projects to use virtme-ng to run custom kernels inside containerized environments, such as github workflows.
This fixes issue #51.

docker support

---

virtme/commands/run.py
virtme_ng/run.py

Add the --numa option to create custom NUMA nodes inside the guest and assign virtual CPUs to them.
Syntax:
--numa MEM[,cpus=FIRST_CPU1[-LAST_CPU1]][,cpus=FIRST_CPU2[-LAST_CPU2]]...
Examples:
- a simple one with 2 NUMA nodes of 2G each:
$ vng -r -m 4G --numa 2G --numa 2G -- numactl -H
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3 4 5 6 7
node 0 size: 1971 MB
node 0 free: 1779 MB
node 1 cpus:
node 1 size: 1950 MB
node 1 free: 1924 MB
node distances:
node   0   1 
0:  10  20 
1:  20  10 
- a more complex one, with a 1GB node and 3GB node, each one with a different non-contiguous set of CPUs assigned:
$ vng -r -m 4G --numa 1G,cpus=0-1,cpus=3 --numa 3G,cpus=2,cpus=4-7 -- numactl -H
available: 2 nodes (0-1)
node 0 cpus: 0 1 3
node 0 size: 1005 MB
node 0 free: 912 MB
node 1 cpus: 2 4 5 6 7
node …

virtme-ng: introduce NUMA support

---

virtme_ng/run.py

Introduce an option to nullify the effect -v/--verbose.
This option can be useful to override certain wrappers / aliases around vng, as pointed out in issue #58.

virtme-ng: introduce -q/--quiet

---

virtme/commands/configkernel.py

Sort of an "RFC" posting. We (netdev) use vng to run networking tests in two flavors - normal and debug. I was surprised to see lockdep splats in the "normal" one.
Commit cd3c35c73624 ("virtme-configkernel: enable lockdep by default") enabled lockdep, and no doubt lockdep is a useful tool. But it's a bit surprising that lockdep is enabled on a normal vng build. I would have expected "vanilla vng build" to be pretty close to kvm_guest.config. lockdep slows down the kernel, eats memory and is not exactly free of false positives.

virtme-configkernel: disable lockdep by default

---

virtme/commands/run.py
virtme/guest/virtme-init
virtme_ng/run.py

Send the return code of the command executed inside the guest to the host.
This allows to run commands inside a guest and give users the impression that they are running on the host.
Examples:
$ vng -r -- true && echo OK || echo ERROR: $?
OK
$ vng -r -- false && echo OK || echo ERROR: $?
ERROR: 1
$ vng -r -- exit 22 && echo OK || echo ERROR: $?
ERROR: 22
This feature is particularly useful for automation/CI, since it easily allows to check the return code of a script executed inside virtme-ng as if it was running directly on the host.
This fixes issue #48.

virtme-ng: channel the return code of a command to the host

---

virtme/architectures.py
virtme/commands/run.py
virtme_ng/run.py

Add a --disable-kvm switch. Some of our testers run without KVM support (nested virt) and developers struggle to repro similarly sluggish execution for their tests. Allow turning KVM off with a single switch even when it's usable.

virtme: let user disable KVM accel easily

---

virtme/guest/virtme-init

Always the host sudoers with a local copy even when running vng with `--user root`, in this way root can also run `sudo` if needed.
Also resync virtme-ng-init to import the same change.

virtme-init: always override sudoers

---

virtme/commands/run.py

If we trigger a kernel panic when running in script mode the guest would just hangs indefinitely.
Test case:
$ vng -vr -- "echo c > /proc/sysrq-trigger"
This can be a bit problematic in a CI scenario, since the indefinite hang can block all the next tests or actions.
A possible solution is to use the `timeout` command with `vng`, but we may also want to distinguish actual timeout conditions from kernel panics.
For this reason always boot the guest with "panic=-1" when running in script mode; this, together with qemu`-no-reboot` will trigger an immediate exit, that can be detected by vng and report the special exit code 255.
This allows to explicitly catch kernel panic conditions, by checking if the return code of vng is 255.
Example:
$ vng -vr -- "echo c > /proc/sysrq-trigger" …

virtme-ng: return 255 on panic in script mode instead of hanging

---

virtme/commands/run.py

Reproducer:
```
$ mkdir -p testdir/arch/x86/boot
$ touch testdir/arch/x86/boot/bzImage
$ virtme-run --kdir testdir
Traceback (most recent call last):
File "/usr/bin/virtme-run", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/lib/python3.12/site-packages/virtme/commands/run.py", line 1388, in main
return do_it()
^^^^^^^
File "/usr/lib/python3.12/site-packages/virtme/commands/run.py", line 803, in do_it
kernel = find_kernel_and_mods(arch, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/virtme/commands/run.py", line 486, in find_kernel_and_mods
kernel.config is not None
^^^^^^^^^^^^^
AttributeError: 'Kernel' object has no attribute 'config'
```
Fix the above by initializing kernel.config right away.

virtme: fix traceback with --kdir when .config doesn't exist

---

setup.py

First, os.listdir("virtme_ng_init") throws an exception when the directory doesn't exist, which is not desirable. Replace it with os.path.exists(), which does the right thing.
Second, it only makes sense to check for the virtme_ng_init submodule when BUILD_VIRTME_NG_INIT != 0, so add it to the conditional.

setup.py: fix logic around the virtme_ng_init submodule

---

virtme/commands/run.py
virtme/guest/virtme-init

Some distro, such as Fedora or CachyOS, are using a higher limit of max open files, beyond the kernel default. Consequently, some applications may expect to operate under this increased limit and, as a result, we may hit EPERM errors in the virtme-ng guest.
Example:
$ sudo su -
sudo: pam_open_session: Permission denied
sudo: policy plugin failed session initialization
...
prlimit64(0, RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=2048*1024}, NULL) = -1 EPERM (Operation not permitted)
...
1048576
Fix this by propagating the value from /proc/sys/fs/nr_open from the host to the vng guest.
This fixes one of the issues reported in #75.

virtme: propagate /proc/sys/fs/nr_open from host to the guest

---

README.md
virtme/guest/virtme-init

Allow to mount legacy cgroup when SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1 is passed to the kernel boot command options.
This mimics systemd's behavior, as specified in the systemd documentation:
```
CHANGES WITH 256 in spe:
...
* Support for cgroup v1 ('legacy' and 'hybrid' hierarchies) is now
considered obsolete and systemd by default will refuse to boot under it.
To forcibly reenable cgroup v1 support, SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1
must be set on kernel command line.
...
```
Moreover, with cgroup v1, only try to mount the same legacy cgroup subsystems supported by systemd (also from the systemd doc):
```
* on cgroup v1: `cpu`, `cpuacct`, `blkio`, `memory`, `devices`, `pids`
```
This was discussed in #84.

init: allow to mount legacy cgroupfs (v1)

---

virtme/guest/virtme-init

When virtme-ng was running as root, the HOME dir was set to '/'.
Now it is set to '/root', the expected value.
Fixes: bcd99d9 ("virtme-init: docker host support")
Similar to https://github.com/arighi/virtme-ng-init/pull/7 but for the old init script.

init: set the HOME env var if root

---

virtme_ng/run.py

By default, `vng --build` and `--kconfig` will not modify existing kconfig, even if new kconfig files are given. The idea is to let people modifying them manually.
It is now possible to force the modification of the kconfig by using '--force'.
Suggested-by: @arighi

vng: override kconfig with '--force'

---

README.md

`virtme` will fallback to `tcg` is KVM cannot be used. That's a shame and it might not be clear that by default, the container will not have access to KVM. An easy way is to launch `docker` with `--privileged`.
While at it, also recommend using Ubuntu 23.10 with virtiofsd.

readme: docker: --privileged and virtiofsd

---

virtme/commands/run.py

When not using the `--graphics` mode, or without the script options, QEmu was always launched with:
-serial none -serial chardev:console
`-serial none` means "don't allocate this serial device". Here, it is directly overridden by another serial. Best not to declare '-serial none' then.
Since QEmu 8.2.2, having `-serial none -serial <something>` is no longer supported, and it is then recommended to remove the unnecessary `-serial none` [1]. It continues to work on previous versions (tested on 8.2.1).
Reported-by: @tehcaster (and others)
Closes: #97
Link: https://lore.kernel.org/qemu-devel/20240122163607.459769-2-peter.maydell@linaro.org/ [1]
Suggested-by: @ishitatsuyuki
Note: I'm not using QEmu 8.2.2 yet, but a few people reported having this issue with it, and a solution has already been …

qemu: remove useless '-serial none' arg

---

virtme/commands/run.py

The Arch Linux qemu-base package depends on the [virtiofsd package](https://archlinux.org/packages/extra/x86_64/virtiofsd/), which installs the binary @ /usr/lib/virtiofsd. This PR adds that path to the possible paths.
I noticed this because qemu appears to use a lot of CPU without virtfiosd, which was making my arch laptop run pretty hot.

Add additional path for virtiofsd executable

---

virtme/commands/configkernel.py

On x86-64 Arch Linux the x86_64-linux-gnu-gcc binary exists and is owned by the gcc package. Since this matches the host arch, this means the heuristic that the existence of such a binary implies that this is a cross-compile is broken.
In addition, Arch linux (for some reason) does not bundle x86_64-linux-gnu-ld so this actually breaks the config generation altogether.
Be a little more cautious and do not specify cross-compilation if we know for sure the gcc prefix refers to the host.

config: avoid accidentally specifying invalid cross-compile

---

virtme/architectures.py

In systems where kvm acceleration cannot be used (e.g, within nested virtualization environments, such as cloud computing, containers, etc.), we might encounter increased boot-time delays resulting from ACPI initialization.
This should be improved if this patch lands upstream: https://lore.kernel.org/qemu-devel/20240417135608.2613586-1-ribalda@chromium.org/T/#u
Meanwhile, it makes sense to consider using the q35 architecture in qemu, instead of the default, when KVM acceleration is not available or unusable, in order to mitigate the ACPI initialization slowdown.
Running some experiments with kvm disabled, also adding '-cpu max' to the equation, and measuring the boot time of multiple virtme-ng runs, shows the following result (average of 10 runs):
machine
+----------------
| default …

virtme: default to q35 architecture when kvm is not available

---

virtme/architectures.py

If RTC is not enabled with the microvm architecture the kernel may end up wasting time to probe the RTC during boot:
[    2.477821] rtc_cmos rtc_cmos: broken or not accessible
[    2.478041] probe of rtc_cmos returned 6 after 1108478 usecs
[    2.478070] initcall cmos_init+0x0/0x90 returned -19 after 1108517 usecs
Make sure to enable the RTC to avoid this unnecessary failure and speed up boot time.
A simple `vng -- uname -r` goes from ~3s to ~0.9s with this change applied using a 6.9 kernel.

virtme: make sure RTC is enabled with microvm

---

setup.py
virtme/commands/configkernel.py

Silent the following lint errors that seems to break CI:
setup.py:84:19: E0606: Possibly using variable 'completion_command' before assignment (possibly-used-before-assignment)
virtme/commands/configkernel.py:338:53: E0606: Possibly using variable 'updatetarget' before assignment (possibly-used-before-assignment)

setup.py: silent lint error

---

virtme/commands/run.py
virtme/guest/virtme-init
virtme_ng/run.py

Use /run to store overlays instead of /tmp.
Require https://github.com/arighi/virtme-ng-init/pull/9 to be merged to keep virtme-ng-init functional.

virtme-ng: export real /tmp to guest

---

virtme/guest/virtme-init

Now that we export the host /tmp inside the guest (#114) we may want to move all the temporary files created by virtme-ng to a different place to avoid mixing them with the host's files.
Therefore, move all the virtme-ng temporary files created during the init phase to /run/tmp.

virtme-ng: move temp files to /run/tmp

---

.gitignore
requirements.txt
setup.py
virtme_ng/run.py

Automatically generate a manpage via argparse-manpage.
We can improve the content of the man page later in the future, but for now it has all the basic information about the command line options and their description, that can be useful when it's not possible to access the main README.md on the github page.
This closes issue #89.

virtme-ng: provide a man page for vng

---

virtme/commands/run.py

On openSUSE based systems, virtiofsd is in /usr/lib/virtiofsd/virtiofsd.
Fix the search path for it.

virtme-ng: fix virtiofsd search path on openSUSE

---

virtme_ng/run.py

Set HOSTCC when `--compiler` is specified and also mark this option as deprecated: setting the corresponding variables in the vng command line is much more intuitive and convenient.
This closes #121.

virtme-ng: deprecated compiler option

---

README.md
virtme/commands/run.py
virtme_ng/run.py

Introduce a `--gdb` option in vng to automatically attach a gdb session to a running instance previously started with `--debug`.
The `--gdb` option implement some automation to figure out the location of vmlinux and provide and easy way to access kernel debugging.
TODO:
- improve the automation to figure out also the sources of the distro kernel searching in some known locations
- support multiple distro (right now vng is looking only for local vmlinux or Ubuntu kernel vmlinux)
This was discussed in #101.

vng: introduce kernel debugging mode

---

virtme/guest/virtme-init

Older kernels don't support the 'xino' overlayfs mount option so we end up with no overlay mounts. Fall back to mounting without that option to work around that. It's not pretty as we end up with errors like:
[    0.380206] overlayfs: unrecognized mount option "xino=off" or missing value
[    0.383246] overlayfs: unrecognized mount option "xino=off" or missing value

init: Fall back to mounting without xino option

---

setup.py

Without this change, when trying to install virtme-ng using pip/pipx would return an error:
...
copying virtme-ng-prompt -> build/bdist.linux-x86_64/wheel/usr/share/bash-completion/completions
copying vng-prompt -> build/bdist.linux-x86_64/wheel/usr/share/bash-completion/completions
creating build/bdist.linux-x86_64/wheel/usr/share/man
creating build/bdist.linux-x86_64/wheel/usr/share/man/man1
error: can't copy 'vng.1': doesn't exist or not a regular file
[end of output]
The vng.1 file will only be generated if argparse-manpages is present, so also include the vng.1 file into data_files only if the package is present.

setup.py: Check if argparse-manpage is present to vng.1

---

virtme_ng/version.py

If virtme-ng is installed from the git repository add git information to the version string.
If, for any reason, we fail to determine the git information (e.g., when building virtme-ng from a distro source package), fallback to the main packaging version, typically updated manually every time we cut a new release.
Suggested-by: Jim Cromie <jim.cromie@gmail.com>

version: generate verison string based on git information

---

virtme_ng/version.py

When we append the git information to the version string we can't simply run git describe from any location, or we may end up getting the version of another git repository (like the kernel).
To prevent this, always run `git describe` from the path where version.py is located: installed vesions will return the plain version as before, while running `vng --version` directly from the git repo will return the version with the additional git information.
Fixes: 5cdb2f0 ("version: generate verison string based on git information")

version: run git describe from the path of the python file

---

virtme_ng/version.py

When we run git describe to append the git information to the version string, make sure that the version.py module is contained in a virtme-ng git repository, to avoid using information from any git repository in any parent directory.
Reported-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>

version: make sure to get the git version from a virtme-ng git repo

---

setup.py
virtme_ng/version.py
vng

If we can't determine any version info from `git describe` try to get the version from pip, otherwise fallback to the hard-coded package version.
Also force to use the git version string both when we are installing (setup.py) the package or when we are directly running vng from the source repo.

version: try to get version from pip

---

virtme_ng/version.py

Now that 'git describe' is only used for local version, it means that in case of issue with the git command, the version from pip cannot be picked as an alternative, because it might be different from the local one being used here. A fallback to the hard-coded package version seems to be the only alternative if 'git describe' cannot be used.
This cover the case of someone using the source code from a tarball, without git support, but potentially having a different version already installed with pip.
Linked to the discussions on #138

version: fallback to `PKG_VERSION` if `git describe` failed

---

Makefile

revision of mk-install sent previously
76d123d (HEAD -> more-version, ghlinux/more-version) Makefile - add install-top-only target
0148f15 run git describe in Makefile
840756b add Makefile install target
adds make install target, 2 different ways (INIT=0/1)
and sets make var from git describe, in the srcdir.
It doesnt handle tarball distros, 
but the git describe, if it works, is from a known location.
ISTM that pip install could capture it to the binary ??

More version - was mk install

---

virtme/commands/run.py

Some distro / kernels require the "debug" boot option to properly show the kernel messages to the console.
Add this parameter to correctly show the kernel log when "-v" is used.
This allows to properly show the kernel log in Arch Linux, CachyOS (and probably most of the Arch-derivative distro).

virtme: pass "debug" to the boot options when running in verbose mode

---

virtme/commands/run.py

It looks like it was accidentally modified [1].
The hypervisor console is supposed to be better, except to debug early console stuff. But that's OK, another serial is used for that: ttyS0 or ttyAMA0, depending on the arch.
Fixes: 4bf382a ("virtme: pass "debug" to the boot options when running in verbose mode")
Link: https://github.com/arighi/virtme-ng/pull/144 [1]

virtme: switch back to hypervisor console

---

setup.py

Instead of re-defining the list of dependencies in setup.py, simply parse them from requirements.txt.
This fixes issue #146.

setup.py: include dependencies parsing requirements.txg

---

virtme/guest/virtme-init

Now the file /run/tmp is only created if the virme_rw_overlay is used.
This will result in errors when virme_rw_overlay is not used. Eg: touch: cannot touch '/run/tmp/fstab': No such file or directory mount: /etc/fstab: special device /run/tmp/fstab does not exist.
dmesg(1) may have more information after failed mount system call.
touch: cannot touch '/run/tmp/lock-frontend'touch: cannot touch '/run/tmp/shadow': No such file or directory : No such file or directorytouch: cannot touch '/run/tmp/lock'touch: : No such file or directorycannot touch '/run/tmp/Lock': No such file or directory /usr/lib/python3/dist-packages/virtme/guest/virtme-init: line 124: /run/tmp/shadow: No such file or directory
[   20.733738] virtme-init: basic initialization done
[   21.507449] virtme-init: starting …

init: Always create /run/tmp folder

---

virtme_ng/run.py

I encountered two issues while using `vng --build --build-host` and thought I'd fix them up. One is due to my use of [git worktrees](https://git-scm.com/docs/git-worktree/en) (so the `.git` is not a directory), and the other was an issue that came up due to the first-time `git push` to my build host.
Thanks for this project, it's really convenient :)

Two fixes for small issues encountered with "--build-host"

---

virtme/commands/configkernel.py

We don't need to enable nvram support by default in the guest and having this disabled can save a few millisec during boot.

virtme-configkernel: disable nvram support

---

MANIFEST.in

Add a MANIFEST.in to include requirements.txt in the source tarball.
This fixes issue #156.

packaging: add MANIFEST.in

---

virtme_ng/run.py

Allow to download -rc precompiled mainline kernels from the Ubuntu mainline kernel repository (https://kernel.ubuntu.com/mainline).
Before:
$ vng -r v6.11-rc7 -- uname -r
v6.11-rc7 does not exist
After:
$ vng -r v6.11-rc7 -- uname -r
6.11.0-061100rc7-generic

vng: allow to use -rc kernels from Ubuntu mainline builds

---

requirements.txt
virtme_ng/version.py

This pr makes two changes to enable installing/running vng via pipx.
pipx is the thing pip install recommends to use to install packages instead of `--break-system-packages`.
(1) it adds setup tools to requirements to fix the following issue:
```
patso in 🌐 ubuntu in virtme-ng on  main via 🐍 v3.12.3 
❯ pipx install .
installed package virtme-ng 1.29+2.gdb83b56, installed using Python 3.12.3
These apps are now globally available
- virtme-configkernel
- virtme-mkinitramfs
- virtme-ng
- virtme-prep-kdir-mods
- virtme-run
- vng
done! ✨ 🌟 ✨
patso in 🌐 ubuntu in virtme-ng on  main via 🐍 v3.12.3 took 3s 
❯ virtme-ng
Traceback (most recent call last):
File "/home/patso/.local/bin/virtme-ng", line 5, in <module>
from virtme_ng.run import main
File …
```

enable virtme-ng to install via pipx

---

virtme_ng/version.py

A recent change has modified how the version was printed. I think the issue was due to the git repo not having any tags, causing an unexpected string, not looking like a version.
Instead, a fallback to the package version is now done when there are no git tags.

Avoid prepending the version with `0.0+dev` all the time

---

virtme/architectures.py
virtme/commands/run.py

Currently is also fails on s390x, but because we fail to detect the kernel version. But this work will also to bring s390x support in the future.

Enable ppc64le to work with "vng -r" argument

---

virtme/architectures.py
virtme/commands/run.py

These two commits enabled us to run ./vng -r on our s390x SLE machines. I'm not sure if there are s390x experts around to double check the "image" naming of the kernel installed on s390x machines, but this is true for SLE.

S390x enablement

---

virtme/architectures.py
virtme/commands/run.py
virtme/cpiowriter.py

No functional change, just coding style cleanups to make lint happy.

Fix lint warnings

---

README.md
virtme/architectures.py
virtme/commands/run.py
virtme_ng/run.py

This PR enables gpu passthrough with virtme-ng.  It adds a new paramemeter "--nvgpu' which is used to provide the PCI address of the gpu.  There are included instructions in the README for enabling VFIO passthrough support.

NVIDIA gpu support

---

virtme_ng/run.py

Properly check if the --cross-compile option has been specified, so that we can correctly use the built-in cross-compile prefixes.
This fixes the cross-architecture builds without using the --cross-compile option.
Fixes: e12dfb2 ("Add cross-compile argument")

virtme-ng: fix incorrect cross-compile override

---

virtme_ng/run.py

The user can specify a directory that does not exist with --root and the tool will create one for him. However, it depends on `lsb_release` which is not available in non-Debian hosts. Therefore, add a hint so the user knows what to do.

Add hint when trying to create root filesystem outside a Debian host

---

virtme/commands/run.py

Regex was changes when it was merged in a single format string, and the parenthesis describing group 1 were lost. Add them back to make sure it matches what we want.
This fixes booting a compressed pre-downloaded kernel on arm64.
Fixes: 3944645 ("virtme: fix regex lint warning")

virtme: fix regex expecting a group

---

virtme_ng/mainline.py

The glob currently matches two vmlinuz when using ubuntu mainline kernels: vmlinuz-6.6.51-060651-generic and
vmlinuz-6.6.51-060651-generic-64k ; but we only need one of the two, otherwise we'll fail with this error:
virtme-run: error: unrecognized arguments: /home/anisse/.cache/virtme-ng/v6.6.51/arm64/boot/vmlinuz-6.6.51-060651-generic-64k
At least this way it should work better, hopefully without breaking other architectures' vmlinuz detection.

virtme-ng: only match a single downloaded kernel on arm64

---

virtme_ng/run.py

Instead of implicitly assuming amd64 as the host architecture, detect it automatically so the user doesn't need to manually specify --arch on non-amd64 systems.
This fixes issue #173.

virtme-ng: auto-detect host architecture

---

virtme_ng/run.py

Allow to export multiple host directories as read-write or read-only into the guest.
This fixes issue #166.

virtme-ng: allow to specify multiple --rwdir and --rodir

---

.github/workflows/pylint.yml
MANIFEST.in
Makefile
README.md
pyproject.toml
requirements.txt
setup.py
virtme_ng/run.py

Remove `requirements.txt`; runtime dependencies are inlined in
`install_requires` in `setup.py` and build dependencies are moved to
`pyproject.toml`.
This allows building with `uv` to succeed.

Modernize build system

---

.github/workflows/pylint.yml
MANIFEST.in
Makefile
README.md
pyproject.toml
requirements.txt
setup.py
virtme_ng/run.py

05f9481b4566f84a26c32be6e0dfb10c64442d5e removed these as the shortest
path to preserving hermeticity of the build, but this solution was
overly aggressive. Restore the bash completions (and the config file) by
placing them in directories inside the package (rather than
system-wide).
Downstream distro packaging can move place the content of ./etc/ in
/etc/ and ./share/ in /usr/share/.
See #181.

Restore bash completions

---

virtme/guest/virtme-init

Current /etc/lvm/ directories are restricted to root only (700), so just create an empty directory and bind mount over. This is enough to make commands like pvcreate to succeed.
It's the same commit as virtme-ng-init, but for virtme-init bash script. What do you think about this approach? Should we first check if the user is root before creating the bind mount?

virtme-init: Enable lvm usage

---

virtme/commands/run.py
virtme/guest/virtme-init
virtme/guest/virtme-udhcpc-script
virtme_ng/run.py

`virtme-run` supports multiple `--net` arguments to setup `virtio-net` devices, but the init program was only starting the DHCP client for one of them: the first one by alphabetical order.
Now, the DHCP client is started for each interface, so each of them can have an assigned IP address.
It is also now possible to specify the bridge interface, with `--net bridge=<br>` option, useful when there are multiple bridges that are created.
While at it, the udhcpc script no longer try to run a wrong command if no router is announced.
Note: this PR depends on https://github.com/arighi/virtme-ng-init/pull/12

 net: support multiple interfaces and different bridges

---

virtme/commands/run.py
virtme_ng/run.py

By default, QEMU sets the first NIC's MAC address to `52:54:00:12:34:56`, and increments the last octet for the next ones. When different VMs need to discuss between each others via the same bridge, that can cause conflicts.
A new option has been added to set a different MAC address, e.g.
--net-mac-address 52:54:00:12:34:56
Which will assign 52:54:00:12:34:56 to the fist NIC, and increment the last octet for the next one, etc.

net: option to force the MAC address

---

.github/workflows/pylint.yml

Python 3.8 has been marked as EoL almost 2 months ago.
Python 3.11, 3.12 and 3.13 have been released.
Link: https://devguide.python.org/versions/

github: pylint: new supported versions

---

README.md
virtme/commands/configkernel.py
virtme/commands/run.py
virtme/guest/virtme-init
virtme_ng/run.py

Having a remote console access can be helpful for different reasons, e.g. an easy way to have multiple terminals, not using a serial which can be slow to print a lot of text, etc.
With this new support, a user can simply use vng like before, and add the new `--vsock` option:
vng --vsock (...)
Then in another terminal, it can connect to the existing VM:
vng --vsock-connect
Advanced users can set a different CID with `--vsock-cid`, useful when multiple VMs are started in parallel.
It is also possible to change the command that is executed when connected inside the VM. By default, `bash -i` is used, but it is possible to pass something else, e.g.
vng --vsock byobu
Or zsh, fish, tmux, etc. Or a script, for example to set env vars, change dir and set other dimensions, etc., e.g. starting the …

feat: vsock support for remote console access

---

README.md
virtme/commands/run.py
virtme/guest/virtme-init
virtme_ng/run.py

Directly connecting to the remote shell using socat launching 'bash' remotely doesn't give a nice user experience: env vars like `$HOME` are not propagated, the terminal size is set to 80x24, the command that is typed is not visible, the directory is not the one picked with --cwd, etc.
To give a better user experience, the `--vsock-connect` option is now creating a script that is setting up the missing pieces. This script is executed when the VM is launched with `--vsock` without any arguments.
Note that it is required to pass info from the host, when launching `--vsock-connect`, to the VM, e.g. for the terminal size. This is done via the script that is executed once connected to the vsock inside the VM. The VM needs access to this script, and the host needs to be able to modify it. Such …

vsock: connect: generate helper script

---

README.md
virtme/commands/run.py
virtme_ng/run.py

Here are a few small improvements for the new `--vsock-connect` feature:
- support environments without tty, e.g. CI.
- execute commands with the right user, not root if the VM was launched with a different user.
- use `su` only if needed: to save ~0.5 sec when executing a command with root.
- `--user` is used if defined
- `--pwd` and `--cwd` are used if defined.

vsock: connect: support no tty, command with right user and no 'su'

---

README.md
virtme/commands/run.py
virtme_ng/run.py

The idea is to have other types of remote connections later on, e.g. SSH. See the discussion on #204.
So to support future types later on, the syntax is now:
vng --server|--client [console|ssh] [--port PORT] [--remote-cmd COMMAND]
The 'ssh' option is not available yet, but by default, 'console' will be used, so users can just do:
$ vng --server
$ vng --client  # in another terminal
A new group for the parser has been added to avoid confusions: `--port` and `--remote-cmd` are linked to `--client` / `--server`.
While at it, the code for the console client/server has been moved to dedicated functions, grouped together. It will also be easy to support a new type later on, simply by calling a different function.
Note that this should only be a refactoring, the behaviour, apart from different …

vsock: rename options to --client/--server

---

README.md
virtme/commands/run.py
virtme_ng/run.py

Introduce a new option `--numa-distance SRC,DST=VAL` to define the distance cost between two NUMA nodes and simulate non-uniform memory access.
Example usage:
```
$ vng -r --cpu 8 -m 4G \
>     --numa 1G,cpus=0-1 --numa 1G,cpus=2-3 \
>     --numa 1G,cpus=4-5 --numa 1G,cpus=6-7 \
>     --numa-distance 0,1=51 --numa-distance 0,2=31 --numa-distance 0,3=41 \
>     --numa-distance 1,2=21 --numa-distance 1,3=61 \
>     --numa-distance 2,3=11 -- numactl -H
available: 4 nodes (0-3)
node 0 cpus: 0 1
node 0 size: 1006 MB
node 0 free: 974 MB
node 1 cpus: 2 3
node 1 size: 953 MB
node 1 free: 919 MB
node 2 cpus: 4 5
node 2 size: 943 MB
node 2 free: 894 MB
node 3 cpus: 6 7
node 3 size: 1006 MB
node 3 free: 965 MB
node distances:
node     0    1    2    3
0:   10   51   31   41
1:   51   10   21   61
2: …
```

numa: introduce --numa-distance

---

.github/workflows/pylint.yml
.github/workflows/run.yml

Not to run the tests twice in a row.
When a branch from the upstream repo is used, the tests are duplicated in the PR: the ones for 'pull_request', and ones for 'push'.
With this modification, it means that the tests are no longer executed when something is pushed, but no PR are created. I guess that's fine, because when something is pushed, it is very likely to have a PR created just after (if it is not already the case).

github: restrict builds on push to the main branch

---

virtme/guest/virtme-init

Ensure udev is started only after all system filesystems have been mounted.
This improves the reliability of virtme-init, as the performance benefit from parallelizing filesystem mounts was negligible. For faster boot times, virtme-ng-init should be preferred, while virtme-init serves as a reliable fallback in case of issues, so prioritizing reliability over performance aligns with virtme-init's role.
This change also resolves networking failures that can occur when using virtme-init.

virtme-init: Start udev after mounting all filesystems

---

README.md
setup.py
virtme/commands/run.py
virtme/guest/virtme-init
virtme/guest/virtme-sshd-script
virtme_ng/run.py

Add support for specifying `--server ssh`, to automatically start and configure sshd in the virtme-ng guest, and `--client ssh` to connect to a virtme-ng guest via SSH.
The server's port can be customized with the `--port NUM` option (default is 2222).
Example usage (start a vng instance with sshd enabled):
$ vng --server ssh --port 2222
In another shell session on the host, connect to the running instance as a client:
$ vng --client ssh --port 2222
Note that it's also possible to use ssh or scp directly, the --client option is provided for convenience and to be consistent with the vsock option.
Edit: additionally, introduce the following shortcuts for convenience, to quickly enable remote connection (either vsock or ssh):
$ vng --console PORT
$ vng --ssh PORT
Example:
```
$ vng --ssh
$ …
```

virtme: enable ssh support

---

virtme/guest/virtme-sshd-script

Only looking if the rootfs is in read-only might not be enough, e.g. if the home directory is mounted in RW.
Instead, we can simply check in which file-system the authorized_keys file is in: if it is in an overlayfs, it is safe.
Note that the '%T' format could be used with stat, but it looks like it is not working with busybox.

sshd: look for overlayfs before modifying auth keys

---

virtme/commands/run.py

It doesn't seem safe to expose the socket to everybody around.
Restrict it to localhost only.
Please note that it also means other users on the same machine can still connect to it. But they will need credentials / keys.
From this discussion: https://github.com/arighi/virtme-ng-init/pull/16#pullrequestreview-2526363654

ssh: only export the port to localhost

---

virtme_ng_init/Cargo.lock
virtme_ng_init/Cargo.toml

Both nix and base64 have newer versions now. base64 0.22 works without changes, nix 0.29 requires features to be listed explicitly, but otherwise also works.

virtme_ng_init: update dependencies

---

virtme_ng_init/src/main.rs

Fix the following warning:
warning: unused return value of `exec` that must be used
--> src/main.rs:978:13
|
978 |             Command::new("bash").arg("-l").exec();
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_must_use)]` on by default
Moreover, check the return code in case exec() fails and log an explicit error before exiting.

virtme-ng-init: always check return code when executing bash

---

virtme_ng/run.py

As mentioned in issue #223, there is no reason to forbid the use of x86_64 as a non-native architecture, so add the proper definition to support x86_64 (building kernel and starting instances) on non-x86 machines.
For consistency with Debian/Ubuntu naming conventions used for other architectures, use amd64 to identify x86_64.
Link: https://lore.kernel.org/all/426d4476-e3b4-4a95-84a1-850015651ee6@kernel.org/
Suggested-by: Catalin Marinas <catalin.marinas@arm.com>

virtme-ng: enable amd64 architecture support on non-x86 platforms

---

virtme_ng/run.py

Without this, a command with simple quotes would be misinterpreted, e.g.
$ vng --console-client --remote-cmd "echo 'foo bar'"
virtme-run: error: unrecognized arguments: bar

console/ssh: properly quote the remote cmd

---

virtme/commands/run.py

As mentioned in #217 it would be nice to always print the output of critical kernel errors (oops / panic), instead of suppressing all the kernel logs completely by default.
Therefore, keep suppressing the boot kernel log, but always dump panic/oops to stderr by default when running in interactive mode.
Example with this change applied:
```
arighi@virtme-ng~/s/linux (master)> vng
_      _
__   _(_)_ __| |_ _ __ ___   ___       _ __   __ _
\ \ / / |  __| __|  _   _ \ / _ \_____|  _ \ / _  |
\ V /| | |  | |_| | | | | |  __/_____| | | | (_| |
\_/ |_|_|   \__|_| |_| |_|\___|     |_| |_|\__  |
|___/
kernel version: 6.13.0-virtme x86_64
(CTRL+d to exit)
arighi@virtme-ng~/s/linux (master)> echo c | sudo tee /proc/sysrq-trigger
[    8.923672] sysrq: Trigger a crash
[    8.923980] Kernel panic - …
```

virtme: always print kernel panic / oops in interactive mode

---

virtme/commands/configkernel.py
virtme_ng/run.py

When looking at the discussion #228, I noticed `vng O=my_dir/` was not working as expected: with `-v`, I could see the VM booting, then stopping right after.
That's because `virtme-run` was called with `--script-sh "O=my_dir/" --kdir=./my_dir/`, so simply setting an env var and exiting.
Now `virtme-run` will be called with `--kdir=my_dir/`, so without `--script-sh` and without the `./` prefix to allow full paths.

Support `vng O=` in interactive mode

---

virtme_ng/run.py

When running with both `--debug` and `--qemu-opts` flags, one space character was missing in the `--qemu-opts` passed on the command line to `virtme-run`.
This could be fixed by adding a space as a prefix for the QEmu arguments added for the `--debug` case, but it sounds better to add the `--qemu-opts` flags at the end, so the debug args don't take precedence.
Closes: #230
Reported-by: @manufactory

vng: support --debug with --qemu-opts

---

virtme_ng/run.py

When passing arguments to `virtme-run`, `--qemu-opts` has to be the last one, because it will take all args set after that.
In other words, `--nvgpu` was not supposed to be passed after `--qemu-opts`.
While at it, re-order functions and add a comment to avoid re-doing the same mistake.
Note that an alternative would be to call `virtme-run` with `--qemu-opt` instead of `--qemu-opts` (with 's'). But a comment should be enough.

vng: support --nvgpu and --qemu-opts

---

virtme_ng/run.py

Because it doesn't make sense to run on a different architecture, but with the host's root FS.
Hopefully this is not going to block weird use-cases.
Link: #233

vng: fail if `--arch` is used without `--root`

---

virtme/commands/configkernel.py

Before this patch, if KBUILD_OUTPUT or O env vars were set, but the mentioned directory didn't exist, the script was first running ...
$ make defconfig
... generating the .config in the build dir, but appending the extra kconfigs in the source dir.
The restriction for the build dir doesn't seem to be needed. Instead, the directory is created if it doesn't already exist.

config: create build dir if defined

---

virtme/guest/virtme-init
virtme_ng_init/src/main.rs

Starting a vng session as regular user doesn't allow to run ping:
```
$ vng --network user
...
$ ping -c1 localhost
ping: socktype: SOCK_DGRAM
ping: socket: Address family not supported by protocol
```
The reason is that by default the kernel restricts the GIDs that are allowed to create raw ICMP sockets:
```
$ sysctl net.ipv4.ping_group_range
net.ipv4.ping_group_range = 1	0
```
Increase the range of allowed GIDs, so that any regular user is able to run ping.
After this change:
```
$ vng --network user
...
$ ping -c1 localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.091 ms
--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.091/0.091/0.091/0.000 ms
``` …

init: allow to create raw ICMP socket as regular user

---

virtme/guest/virtme-init
virtme_ng_init/src/main.rs

When running vng in graphic mode (-g), recent versions of Xorg may fail to start with the following error:
```
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
```
This can happen because the host's /tmp is exposed to the guest and Xorg might get confused finding a previous state.
Fix by removing the Xorg state files before starting the X server in the vng guest.
Fixes: da5b586 ("virtme-ng: export real /tmp to guest")

init: clean up previous X11 state

---

setup.py

When using vng on a filesystem different than the host's filesystem (when `--root DIR` is used) we may have a different glibc version or different libraries in general, that are not compatible with the pre-built virtme-ng-init.
To fix this build a static virtme-ng-init, so that it can be used across any rootfs.
This fixes #243.

setup.py: Build a static virtme-ng-init

---

virtme/commands/run.py
virtme_ng/run.py

Note: I'm not sure how to name the command line option.
Sometimes the user is not interested in having a QEMU monitor, therefore let's add this option. This changes for example the 'CTRL-a' behavior on the console.

run: Add '--disable-monitor'

---

pyproject.toml

Building vng using pip 25.0.1 triggers a bunch of errors. Update pyproject.toml to make pip happy.

build: support newer pip

---

.pre-commit-config.yaml

This avoids to run the 'end-of-file-fixer' hook on the 'DCO-1.1.txt' file.
Before this change:
```
$ pre-commit run --all-files
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook
Fixing DCO-1.1.txt
trim trailing whitespace.................................................Passed
check for merge conflicts................................................Passed
mixed line ending........................................................Passed
check that executables have shebangs.....................................Passed
check that scripts with shebangs are executable..........................Passed
pyupgrade................................................................Passed …
```

pre-commit: Avoid removing the blank line from DCO-1.1.txt

---

Makefile

virtme_ng_init is no longer in a submodule, this target is no longer needed because these files should always be there and no longer need to be generated with a command.
Closes: #270

make: drop submodule update

---

setup.py
virtme/resources.py

pkg_resources has been deprecated in Python v3.12.
Switch to importlib_resources instead.
We only need the path, not to read from these resources. So hopefully, this simple conversion can be applied.
Link: https://importlib-resources.readthedocs.io/en/latest/migration.html

resources: replace pkg_resources by importlib_resources

---

README.md

This is handy because it is shorter than `ssh -F ~/.cache/virtme-ng/.ssh/virtme-ng-ssh.conf`.

README: mention 'ssh vsock/<CID>'

---

virtme/commands/configkernel.py

Currently, configkernel starts preparing a new config, and afterwards checks if one exists.  With --verbose, this is quite noisy, obscuring the "have .config, no changes made" message which follows.
Move the "wheres-config" code (both KBUILD_OUTPUT and make O=..) above the "gen-config" code to avoid the useless work and noise entirely.
Here it is, working for me:
```
jimc@frodo:~/projects/lx/wk-A$ vng -bv O=./buz
cmd: virtme-configkernel --defconfig --verbose --no-update O=./buz make[1]: Entering directory '/home/jimc/projects/lx/wk-A/buz' missing ./buz/Makefile, adding -f $src/Makefile
adding make_args: ['-f', '/home/jimc/projects/lx/wk-A/Makefile']
GEN     Makefile
HOSTCC  scripts/basic/fixdep
HOSTCC  scripts/kconfig/conf.o
HOSTCC  scripts/kconfig/confdata.o
HOSTCC …
```

configkernel: check for an existing .config before doing new one

---

README.md

The syntax is incorrect for the given 'virtme-ng.conf' example in the README.md.

README.md: Improve `virtme-ng.conf` example

---

virtme/commands/run.py

When using a different root filesystem, e.g. when dealing with cross builds, the /lib/modules/<KVER> link created to .virtme_mods is dead since it points to outside the root. Fix by setting kernel.use_root_mods when the user pass the top-level `--root` argument.
Fixes: #141

virtme/run: Set kernel.use_root_mods when user pass `--root`

---

virtme/commands/run.py

'socat' is used to connect to the guest via VSOCK.
Instead of throwing a FileNotFoundError exception because 'socat' is not available, abort before with a more comprehensive message.

console: abort if socat is not available

---

virtme/commands/run.py

When running in a container with limited privileges, some procfs files may be inaccessible (e.g., /proc/sys/fs/nr_open), triggering permission denied errors.
In such cases, ignore the error and continue, so that we can still get a functional vng session.

virtme/commands/run: Do not fail if nr_open can't be accessed

---

README.md
cfg/virtme-ng.conf
setup.py
virtme/commands/run.py
virtme/guest/virtme-init
virtme_ng/run.py
virtme_ng/utils.py
virtme_ng_init/src/main.rs

Hello!
First of all, I'm using vng for testing local builds of [LTP](https://github.com/linux-test-project/ltp) and it's such an amazing tool! Thank you for maintaining it!
One of these days I was trying to run a test which required systemd and realized it was unfortunately not the right tool for the job... Then I saw mentions of adding support for it [here](https://lwn.net/Articles/951313/) and [here](https://github.com/arighi/virtme-ng/discussions/193). I would like to get the ball rolling on this, but I didn't know where to start. I hacked away a very ugly solution and would like to ask for guidance about how to approach this problem and refine it.
Basically, the idea is to add a `--systemd` option argument (that only makes sense currently when in use with `--root`) which would then …

Add support for systemd

---

setup.py

With Python 3.13, I get these warnings when running `make`:
```
/usr/lib/python3/dist-packages/setuptools/config/_apply_pyprojecttoml.py:61: SetuptoolsDeprecationWarning: License classifiers are deprecated.
!!
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: GNU General Public License v2 (GPLv2)
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
!!
dist._finalize_license_expression()
/usr/lib/python3/dist-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
!! …
```

setup: fix license format

---

virtme/commands/run.py

Even if it is unlikely to have spaces in this command (maybe the kernel dir?), it seems better to use 'shlex' like it is done for the other commands.

gdb: dry-run: use 'shlex' to print array

---

virtme/guest/virtme-init
virtme_ng/run.py
virtme_ng_init/src/main.rs

Introduce a `--shell` option to override the default shell from `/etc/passwd` when launching a user session inside the vng guest.
This allows starting the guest session with an alternative shell or program (i.e., tmux).
Example:
```
$ vng --shell /bin/bash
...
$ echo $SHELL
/bin/bash
$ vng --shell /bin/fish
...
> echo $SHELL
/bin/fish
```
This addresses issue #346.

virtme-ng: Introduce --shell

---

virtme/architectures.py

Certain AMD CPUs require topology extensions (topoext) to be enabled to expose extra CPU topology information to the virtme-ng guest, such as threads per core and accurate core/socket layout.
Enable it by default both for x86 and microvm architectures. This allows to properly enable SMT inside virtme-ng guests on AMD CPUs.
On non-AMD CPUs, topoext is ignored, therefore it's safe to enable it unconditionally by default.

virtme/architectures: Enable topology extensions for AMD CPUs

---

virtme/commands/run.py

Kernels built with the default virtme-ng configuration lack zram support, so starting the zram service can hang the systemd boot.
Prevent the hang by implicitly disabling the zram service (system.zram=0).
This fixes a boot hang issue in CachyOS when using --systemd.

virtme: systemd: Disable zram service

---

virtme/commands/run.py

`re.search(...)` expects a string as the second argument, therefore let's convert the Path into a string.
$ ./vng -r
Traceback (most recent call last):
File "/home/mhartmay/storage/git/virtme-ng/virtme-run", line 18, in <module>
sys.exit(run.main())
^^^^^^^^^^
File "/home/mhartmay/storage/git/virtme-ng/virtme/commands/run.py", line 2028, in main
return do_it()
^^^^^^^
File "/home/mhartmay/storage/git/virtme-ng/virtme/commands/run.py", line 1198, in do_it
kernel = find_kernel_and_mods(arch, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/mhartmay/storage/git/virtme-ng/virtme/commands/run.py", line 575, in find_kernel_and_mods
kver = get_kernel_version(kimg, img_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/mhartmay/storage/git/virtme-ng/virtme/commands/run.py", line 520, in …

virtme/commands/run: Fix TypeError
